package model;
public abstract class DataConstants {
    protected static final String USER_ID = "id";
    protected static final String USER_FILE_NAME = "src/main/java/model/.json/users.json"; // Changed from: ".json/users.json"
    protected static final String COMPANY_FILE_NAME = "src/main/java/model/.json/company.json"; // Changed from: ".json/company.json"
    protected static final String TASK_FILE_NAME = "src/main/java/model/.json/task.json"; // Changed from: ".json/task.json"
    protected static final String USER_EMAIL = "email";
    protected static final String USER_PASSWORD = "password";
    protected static final String USER_FIRST_NAME = "firstName";
    protected static final String USER_LAST_NAME = "lastName";
    protected static final String USER_ROLE = "role";
    protected static final String USER_COMPANIES = "companies";
    protected static final String COMPANY_NAME = "name";
    protected static final String COMPANY_ID = "id";
    protected static final String COMPANY_BOARDS = "boards";
    protected static final String COMPANY_USERS = "users";
    protected static final String COMPANY_ADMINS = "admins";
    protected static final String TASK_ID = "taskid";
    protected static final String TASK_NAME = "name";
    protected static final String TASK_DESCRIPTION = "description";
    protected static final String TASK_DATE = "date";
    protected static final String TASK_AUTHOR_ID = "authorid";
    protected static final String TASK_ASSIGNEE_ID = "assigneeid";
    protected static final String TASK_CATEGORY = "category";
    protected static final String TASK_RESOLVED = "resolved";
    protected static final String TASK_PRIORITY = "priority";
    protected static final String TASK_TIME_REQUIRED = "time-required";
    protected static final String TASK_HISTORY = "history";
    protected static final String HISTORY_AUTHOR_ID = "authorid";
    protected static final String HISTORY_CHANGE = "change";
    protected static final String HISTORY_DATE = "date";
    protected static final String TASK_COMMENTS = "comments";
    protected static final String COMMENTS_ID = "authorid";
    protected static final String COMMENT = "comment";
    protected static final String COMMENT_DATE = "date";
    protected static final String COMMENT_COMMENTS = "comments";
    protected static final String BOARD_TITLE = "title";
    protected static final String BOARD_DESCRIPTION = "description";
    protected static final String BOARD_COMMENTS = "comments";
    protected static final String BOARD_COLUMNS = "columns";
    protected static final String BOARD_PRIVATE = "private";
    protected static final String BOARD_SCRUM_MASTER = "scrumMaster";
    protected static final String BOARD_PRODUCT_OWNER = "productOwner";
    protected static final String BOARD_DEVELOPERS = "developers";
    protected static final String COLUMN_TITLE = "title";
    protected static final String COLUMN_DESCRIPTION = "description";
    protected static final String COLUMN_TASKS = "tasks";
}
